- name: Install docker and docker-compose
  pip:
    name: 
    - docker
    - docker-compose

- name: Clone git repository
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: Run docker-compose
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
    debug: yes